# Generated by Django 6.0.7 on 2026-07-18 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=40)),
                ('name_ne', models.CharField(max_length=40)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name_en', models.CharField(max_length=80)),
                ('name_ne', models.CharField(max_length=80)),
                ('province', models.CharField(max_length=40)),
                ('centroid_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('centroid_lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='CropCalendarWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_of_year', models.PositiveSmallIntegerField()),
                ('stage', models.CharField(choices=[('fallow', 'Fallow'), ('land-prep', 'Land preparation'), ('sowing', 'Sowing / transplanting'), ('vegetative', 'Vegetative growth'), ('flowering', 'Flowering'), ('grain-fill', 'Grain fill / maturity'), ('harvest', 'Harvest'), ('post-harvest', 'Post-harvest')], max_length=30)),
                ('risk_notes_en', models.TextField(blank=True, default='')),
                ('risk_notes_ne', models.TextField(blank=True, default='')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_weeks', to='calendar_app.crop')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_weeks', to='calendar_app.district')),
            ],
            options={
                'ordering': ['week_of_year'],
                'constraints': [models.UniqueConstraint(fields=('district', 'crop', 'week_of_year'), name='uniq_district_crop_week'), models.CheckConstraint(condition=models.Q(('week_of_year__gte', 1), ('week_of_year__lte', 53)), name='week_between_1_53')],
            },
        ),
    ]
