"""
API views.

Optimization decisions:
- select_related on calendar queries (avoid N+1).
- Compare endpoint returns crops in ONE response keyed by crop code —
  the frontend renders side-by-side from a single request.
- /advisory/current returns the freshest stored advisory; if none exists
  yet (cold start) it generates one on-demand, then falls back to a
  503 payload if Open-Meteo is down. Advisories are pre-generated by the
  weekly job, so on-demand generation is the exception, not the rule →
  no per-request external API latency in the normal path.
- /advisory/regenerate is token-protected (simple header token; the JD
  scope doesn't warrant full user accounts for a single ops endpoint).
"""
from django.conf import settings
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from advisory.open_meteo import generate_all, generate_for_district
from calendar_app.models import Crop, CropCalendarWeek, District

from .serializers import (
    CalendarWeekSerializer,
    CropSerializer,
    DistrictSerializer,
    WeeklyAdvisorySerializer,
    localize,
)


def _lang(request):
    lang = request.query_params.get("lang")
    return lang if lang in ("en", "ne") else None


@api_view(["GET"])
def district_list(request):
    data = DistrictSerializer(District.objects.all(), many=True).data
    return Response(localize(data, _lang(request)))


@api_view(["GET"])
def crop_list(request):
    data = CropSerializer(Crop.objects.all(), many=True).data
    return Response(localize(data, _lang(request)))


def _get_or_none(model, **kwargs):
    try:
        return model.objects.get(**kwargs)
    except model.DoesNotExist:
        return None


@api_view(["GET"])
def calendar_view(request):
    d_slug = request.query_params.get("district")
    c_code = request.query_params.get("crop")
    if not d_slug or not c_code:
        return Response(
            {"detail": "district and crop query params are required"},
            status=status.HTTP_400_BAD_REQUEST,
        )
    district = _get_or_none(District, slug=d_slug)
    crop = _get_or_none(Crop, code=c_code)
    if not district or not crop:
        return Response({"detail": "Unknown district or crop"}, status=404)

    weeks = CropCalendarWeek.objects.filter(district=district, crop=crop).order_by(
        "week_of_year"
    )
    payload = {
        "district": DistrictSerializer(district).data,
        "crop": CropSerializer(crop).data,
        "weeks": CalendarWeekSerializer(weeks, many=True).data,
    }
    return Response(localize(payload, _lang(request)))


@api_view(["GET"])
def calendar_compare(request):
    d_slug = request.query_params.get("district")
    crops_param = request.query_params.get("crops", "")
    codes = [c.strip() for c in crops_param.split(",") if c.strip()][:3]
    if not d_slug or len(codes) < 2:
        return Response(
            {"detail": "district and at least two crops are required (crops=a,b)"},
            status=status.HTTP_400_BAD_REQUEST,
        )
    district = _get_or_none(District, slug=d_slug)
    if not district:
        return Response({"detail": "Unknown district"}, status=404)

    crops = list(Crop.objects.filter(code__in=codes))
    if len(crops) != len(codes):
        return Response({"detail": "One or more unknown crops"}, status=404)

    weeks = (
        CropCalendarWeek.objects.filter(district=district, crop__in=crops)
        .select_related("crop")
        .order_by("crop__code", "week_of_year")
    )
    by_crop = {c.code: [] for c in crops}
    for w in weeks:
        by_crop[w.crop.code].append(CalendarWeekSerializer(w).data)

    payload = {
        "district": DistrictSerializer(district).data,
        "crops": {c.code: CropSerializer(c).data for c in crops},
        "calendars": by_crop,
    }
    return Response(localize(payload, _lang(request)))


@api_view(["GET"])
def advisory_current(request):
    d_slug = request.query_params.get("district")
    if d_slug:
        district = _get_or_none(District, slug=d_slug)
        if not district:
            return Response({"detail": "Unknown district"}, status=404)
        adv = district.advisories.first()  # ordering = -for_week
        if adv is None:
            adv = generate_for_district(district)
        if adv is None:
            return Response(
                {"detail": "Advisory unavailable (forecast source down)"}, status=503
            )
        return Response(localize(WeeklyAdvisorySerializer(adv).data, _lang(request)))

    # All districts (advisory dashboard)
    latest = []
    for district in District.objects.all():
        adv = district.advisories.first()
        if adv is None:
            adv = generate_for_district(district)
        if adv is not None:
            latest.append(WeeklyAdvisorySerializer(adv).data)
    return Response(localize(latest, _lang(request)))


@api_view(["POST"])
def advisory_regenerate(request):
    token = request.headers.get("X-Regen-Token", "")
    if token != settings.ADVISORY_REGEN_TOKEN:
        return Response({"detail": "Invalid token"}, status=status.HTTP_401_UNAUTHORIZED)
    count = generate_all()
    return Response({"regenerated": count})
