# Generated by Django 6.0.7 on 2026-07-18 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_week', models.DateField(help_text='Thursday of the ISO week')),
                ('tmax_avg_c', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tmin_avg_c', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('precip_total_mm', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('summary_en', models.TextField(blank=True, default='')),
                ('summary_ne', models.TextField(blank=True, default='')),
                ('daily', models.JSONField(blank=True, default=list, help_text='7-day detail for sparklines')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='calendar_app.district')),
            ],
            options={
                'verbose_name_plural': 'weekly advisories',
                'ordering': ['-for_week'],
                'constraints': [models.UniqueConstraint(fields=('district', 'for_week'), name='uniq_district_week_advisory')],
            },
        ),
    ]
